### ISSUE TITLE
Google Cloud Profile Picture Does Not Display

### ISSUE THREAD

**Issue by adamkpumputis** [HappyHobby/HappyHobby#68] opened 2020-06-07 22:09 UTC
Issue:

After signing into HappyHobby with a google account the Google Cloud Profile Picture does not appear on the navbar. When selecting the user profile name the Google Cloud Picture does not show up on the drop-down menu

Reproduction steps:

Sign in to HappyHobby using an existing google account
select profile on top right of nav bar

Screenshot:

![Screen Shot 2020-06-07 at 3 09 28 PM](https://user-images.githubusercontent.com/22605317/83981234-f082f680-a8d0-11ea-8798-6f81a26ed133.png)
![Screen Shot 2020-06-07 at 3 09 40 PM](https://user-images.githubusercontent.com/22605317/83981235-f24cba00-a8d0-11ea-9e0a-c1ae5b4da34b.png)

**Comment by thejameskim** [comment] 2020-06-07 22:57
Thanks for your report. Downgrading this to an enhancement tag and not a bug because not having the picture does not prevent the user from accomplishing the task. We also edited our requirements to not include the picture as collecting images for the non-Google accounts were out of scope, so for this release, we will not be including images anyways as we would need to include image collection in account creation.

**Closed** 2020-06-07 23:05 UTC
Labels: enhancement, minor, wontfix
